### ISSUE TITLE
Use autocxx perhaps?

### ISSUE THREAD

**Issue by bagavi** [light-curve/ceres-solver-rs#12]
I was wondering if you had considered using [`auto-cxx` ](https://docs.rs/autocxx/latest/autocxx/) to create a direct cpp-rust bridge?
Many tasks will become simpler

**Comment by hombit** [comment]
Hi @bagavi, this project is my first binding crate, so I decided to try simple things first: the first attempt was bindgen for the C-API, the second is manual cxx wrapping for a part of the C++ API. Generally, I like auto-cxx idea, but I don't have reasons to do it right now: the crates do all I need already, and I see no issues/PRs showing someone else's interest to this project.

**Comment by hombit** [comment]
It would be useful if you give an example of how auto-cxx implementation could help solving your problems.

**Comment by hombit** [comment]
While I think that `auto-cxx` may help I close it for now because I have no time and motivation to investigate this path. Please feel free to reopen when you have new arguments.
